### ISSUE TITLE
Port all test cases to Saft\TestCase class

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#16]
It provides basic information and helper functions. Maybe we create specialized test classes for each backend. For instance all store related ones will need authentication credentials from the test-config.yml, so there has to be a function which helps read it.

**Comment by white-gecko** [comment]
Is this necessary or should we see if there is some other solution of adding our own assertions to phpunit?

**Comment by k00ni** [comment]
I think we really should use our own very basic TestCase which extends PHPUnit_Framework_TestCase, because we can extend it later on and are more flexible. But you are right, some kinds of test cases need certain assertions, so we could extend TestCase and add them.

**Comment by k00ni** [comment]
While port all tests, i move TestCase.php to Saft\Test namespace.

**Comment by white-gecko** [comment]
I think we should provide all assertions in one class if we extend `PHPUnit_Framework_TestCase`

**Comment by k00ni** [comment]
> I think we should provide all assertions in one class if we extend PHPUnit_Framework_TestCase

As it is now. That's fine for me too.

**Comment by k00ni** [comment]
Done with 62d853e.
