### ISSUE TITLE
Create a factory-solution / start using dependency injection

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#17]
We need factories for all classes. Furthermore we will start using DI to improve the factory solution.
- [x] NodeFactory
- [x] StatementFactory
- [x] CacheFactory
- [x] ~~StoreFactory~~ - It needs a DI-container to work. But we wont introduce one at the framework level, so we decided to remove it.
- [x] ParserFactory
- [x] SerializerFactory
- [x] ~~ChainFactory (see #6)~~ - Will not be created. Reason for that is [here](https://github.com/SaftIng/Saft/issues/17#issuecomment-103046239).
- [x] QueryFactory
- [x] ResultFactory
- [x] StatementIteratorFactory

**Comment by white-gecko** [comment]
Introduced NodeFactory in dffae7e02d6afd9d0e063ddfe36f4827f53c475b and StatementFactory in b0c3bebc247bfaa6ccc149a5b74e87cb2bda4aa1

**Comment by k00ni** [comment]
CacheFactory was introduced in f9c13bc.

**Comment by white-gecko** [comment]
So we still need StoreFactory (Maybe this is somehow the same as Store Chain), ParserFactory and SerializerFactory

**Comment by k00ni** [comment]
StoreFactory was introduced in 863cfef.

**Comment by k00ni** [comment]
ChainFactory was introduced in db5e30d.

**Comment by k00ni** [comment]
As discussed with you few days ago, we wanna switch to DI and maybe abandon the factory classes, because they do not really add value to Saft.

I am currently playing around with [Dice](https://github.com/TomBZombie/Dice). It has a good documentation and seems to be the fastest DI container and even factory solution out there. Have a look for yourself: https://r.je/dice.html

Thinking about a wrapper for Dice, so that a user can use our classes + Dice, without to know about rules and such stuff. So he ends up using something like:

```
$dic = new Saft\DI\DIC();
$dic->create('Virtuoso');
```

I dont know, lets see, ... i am still reading :)

I'd like to place further experiments with Dice in the **feature/di-dice** branch.

**Comment by k00ni** [comment]
Maybe we should let the factories live, but use the dice-container inside them to create the instances we want. If we remove the factories and we need, lets say, an instance of NamedNode, you have to know the exact name of that at the point you need it. With a factory as a layer between the NamedNode implementation and the code where we need it, we keep loose coupling.

**Comment by k00ni** [comment]
I pushed some commits recently in which i ported all existing factories to dice. 

#### About the initialization of Store instances

I just had an idea, but it might by not strict enough for you. In Dice it is possible to specify additional parameters given to a new instance. Here is the [doc](https://r.je/dice.html#example1-2).

With the last changes of mine, you can already create new instances of everything by just do:

```
$dice = new Dice();
$instance = $dice->create('classname');
```

We discussed earlier about how to specify the initialization of a Store instance. My approach with dice would be, to not add a new entry to the Store interface (e.g. a certain __construct method), but made clear to the user (in the documentation) that if he wants to create a new Store class, the constructor has to do the init-work and must have the following structure: first all parameter which represent classes, after that everything else.

For instance:

```
class Foo implements Store {
    public function __construct(NodeFactory $nf, ... array $config, ...)
```

$nf is one of the parameter which represents a class. $config is one of the others. That said, we can now use Dice to instance foreign Store instances very easily, even with our StoreFactory:

```
class StoreFactoryImpl {
    public function createInstance($classname, $parameter){
        return $this->dice->create($classname, $parameter);
```

So we keep the parameter specification in the Foo class, as you requested, and gain the ability inject Store instances, without _knowing_ their exact constructor parameter list.

What you think?

**Comment by white-gecko** [comment]
I think we can not specify the constructor parameters in any interface and as I understand the whole thing a factory would exactly know the parameters of the classes it is instantiating while all factories of a kind are using the same interface (abstract factory).
Maybe we should create an example application or an integration test, which parses some file, loads the data into a store runs some queries on this data edits the data. With this we should see all the missing parts and how we actually need to deal with the dependencies. And if everything is done as dynamic as we want it, it should be easily possible without changing the actual code of this example, to replace the backends: store (Virtuoso vs. ARC2) and the parser (Redland vs. something else) without the need to change the business logic code.

**Comment by k00ni** [comment]
I think i finally got all cases covered, which are interesting for us using Dice's auto injection. Here are all we now covered: 

### Create an instance of a class

```
class A {
}

$dice = new \Dice\Dice;
$a = $dice->create('A');
```

Dice does everything for you. Trivial.

### Create an instance of a class, which needs instances of other classes

That's the usual case i think. Assume:

```
class MyClass {
    public function __construct(PDO $pdo) { }
}

$dice = new \Dice\Dice;
$myclass = $dice->create('MyClass');
```

In that case Dice will automatically creates an instance of PDO and pass it as first argument. It works recursive too.

If you want to pass the same instance everytime a class needs PDO, have a look in the Dice [Doc](https://r.je/dice.html#example2).

### Create an instance of a class, which has Interface(s) as constructor parameters

An example is the creation of an LiteralImpl instance, using [NodeFactoryImpl->createInstance](https://github.com/SaftIng/Saft/blob/feature/di-dice/src/Saft/Rdf/NodeFactoryImpl.php#L16). 

The constructor of LiteralImpl want:

```
public function __construct($value, Node $datatype = null, $lang = null)
```

The second parameter $datatype is of type Node, which is an interface. So we have to tell Dice how to handle that. Here come rules to play. I used two different rules with [constructParams](https://r.je/dice.html#example3-3) and [substitutions](https://r.je/dice.html#example3-1).

A rule tells Dice about certain configurations to use to override automatic injection. You can see how i implement it [here](https://github.com/SaftIng/Saft/blob/feature/di-dice/src/Saft/Rdf/NodeFactoryImpl.php#L16). In the following i give you a summary.

```
// this tells Dice only, that an associated class has to be instantiate using the 
// following constructor parameter (see addRule at the bottom for more info)
$ruleNamedNode = new \Dice\Rule();
$ruleNamedNode->constructParams = array('http://www.w3.org/1999/02/22-rdf-syntax-ns#langString');

// this tells Dice, that an associated class has to be instantiate using the 
// following constructor parameter AND that each occurrences of Node
// have to be replaced with an instance of Saft\Rdf\NamedNodeImpl 
$ruleLiteral = new \Dice\Rule();
$ruleLiteral->constructParams = array('literal value', 'de_DE');
$ruleLiteral->substitutions['Saft\Rdf\Node'] = new \Dice\Instance('Saft\Rdf\NamedNodeImpl');

// the rules above are worthless alone, but now we connect them to certain classes.
// if you create one of these classes using this $dice instance, the rules above will 
// take effect
$dice = new \Dice\Dice();
$dice->addRule('Saft\Rdf\NamedNodeImpl', $ruleNamedNode);
$dice->addRule('Saft\Rdf\LiteralImpl', $ruleLiteral);

$literal = $dice->create('Saft\Rdf\LiteralImpl');
```

I hope it is more clear now how this works. I have to admit, that this style of object-creation is really weird at the beginning, but totally logical if you know what to do.

**Comment by k00ni** [comment]
I almost forgot to say that Dice is very flexible by parsing the constructor. What i mentioned before:

```
class Foo implements Store {
    public function __construct(NodeFactory $nf, ... array $config, ...)
```

about a certain _style_ of the constructor, is really **not** necessary. You can call 

```
$dice->create($classname, $parameter);
```

and it picks the right item from $parameter and use it for the right parameter in the constructor. It can compute when to auto inject a class instance and when and where to use one of that items from $parameter.

**Comment by k00ni** [comment]
I added some examples to demonstrate DI using Dice: 

https://github.com/SaftIng/Saft/tree/feature/di-dice/examples/DependencyInjection

**Comment by white-gecko** [comment]
Ok, looks good. So I think the rulse will be constructed based on some configuration, which defines which implementations are used.

I think the last line in the last example in https://github.com/SaftIng/Saft/issues/17#issuecomment-102415149 should be

```
$literal = $dice->create('Saft\Rdf\Literal');
```

instead, if I understand the things correctly. But does it also support namespaces, so one could use

```
$literal = $dice->create('Literal');
```

use instead?

Further I think actually Nodes should not be instantiated in this way, but NodeFactories should be used for that.

If I get the whole dependency injection container task correctly it will only be used when actually implementing applications rather than anywhere in the library?

**Comment by k00ni** [comment]
> So I think the rulse will be constructed based on some configuration, which defines which implementations are used.

Yes. We are totally flexible here. 

> I think the last line in the last example in #17 (comment) should be
> $literal = $dice->create('Saft\Rdf\Literal');

No. Because Literal is an interface, which can not be instantiated by Dice directly, you have to give him a class which implements it. Otherwise an exception will be thrown, because of that.

> But does it also support namespaces, so one could use
> $literal = $dice->create('Literal');

No, not to my knowledge, but it could be, maybe in branch _master_ (for PHP 5.6+)? For the moment the namespace must be part of the class name. 

> Further I think actually Nodes should not be instantiated in this way, but NodeFactories should be used for that.

Yeah, you are right. My intention was to provide two ways of class instantiation:
1. **Create instances using a Saft factory, such as NodeFactoryImpl:** Easy peasy, you just use a factory, call a function, receive a ready-to-use instance. With the factories, we provide a _standard_ way how to use Saft classes. (We already talked about that point a few times.)
2. **Use Dice directly to instantiate your classes:** Needs more insight, but you are free to do whatever you want. In that way the developer can configure the DI as he wants it. That is interesting if you want to integrate Saft in another framework/lib/... and it has to act in a certain way.

I strongly suggest that we use Dice to create the remaining factories. After we finished them, we have a good DI strategy, good implementation and are finished with that issue, aren't we?

**Comment by k00ni** [comment]
We decided, that we do not wanna use Dice at this level. Using a DI-container makes sense for the application level, where you want to put Saft and your application/business logic together.

Therefore:
- Remove **StoreFactory** (+ Impl-class) - It which needs a DI-container to work. But we wont introduce one at the framework level, so we decided to remove it.
- Remove **ChainFactory** (+ Impl-class) - Because it depends on the StoreFactory and to use ChainFactory effectively you need a fixed way to create Store instances. 
- Remove **di-dice** branch
- If we ever need a DI-container, we prefer Dice because it does not force you to annotate your code (e.g. with @) and is very lightweight.

That decision also mean, that we keep program in the same way as we did, by giving fresh instances into a class only via constructor. New-calls are only allowed when you instantiate such a class which needs certain instances, such as QueryCache, which needs an instance of CacheFactory. But if you instantiate QueryCache directly, you at a level where you want to use it directly, so you can do it the _old way_:

```
new QueryCache(new ..., ... );
```

or you use a DI-container like Dice:

```
$dice = new Dice();
$dice->create('Saft\QueryCache\QueryCache');
```

which does most of the init-part for you.

**Edit**: 3:10 pm, added "Remove ChainFactory"

**Comment by white-gecko** [comment]
So if we understand each other correctly one will not call `new CacheFactory` within `QueryCache` but will instantiate query-cache e.g. with

```
new QueryCache(new CacheFactory, ... );
```

resp. with Dice.

**Comment by k00ni** [comment]
Yes.

I changed the old behavior to not call _new CacheFactoryImpl_ inside QueryCache. (related [commit](https://github.com/SaftIng/Saft/commit/4b300f3d151952fde75077331c3f279f17f4a2d2#diff-c1734844d2a1da6cd5e4a9d064a77249R83))

**Comment by k00ni** [comment]
QueryFactory introduced in 4b300f3.

**Comment by white-gecko** [comment]
So Next factory to discuss `ResultFactory` :-)

Do we need a `ResultFactory` or will each store just output its own implementation of `Result`?

**Comment by k00ni** [comment]
ResultFactory was introduced in 841e8ec.

> Do we need a ResultFactory or will each store just output its own implementation of Result?

We talked about this already, so i just explain it here for documentation purpose. In backends ARC2 and Virtuoso a Result infrastructure is needed, for instance to create StatementResult or ValueResult. Both backends are very generic in a way to be able to use the existing standard Result implementation of Saft\Store\Result. So it would be additional work for me as a backend developer to write my own implementation. That should only be the case if the standard implementation does not fit my needs.

**Comment by k00ni** [comment]
Do we need an IteratorFactory?

**Comment by white-gecko** [comment]
Good question. This will result in three dependencies, if a component is working with nodes ... But yes, why not.

**Comment by k00ni** [comment]
Commit 5fb861d introduced ParserFactory.

**Comment by k00ni** [comment]
Commit 95d60b0 introduces SerializerFactory + standard implementation for nquads and ntriples serialization.

**Comment by k00ni** [comment]
StatementIteratorFactory introduced in 22464d0.

**Comment by k00ni** [comment]
So, i think we have the most important factories. No questions unsolved, can we close this?

**Comment by white-gecko** [comment]
Yes I think it should be fine for now. Else we should reopen it later.
