### ISSUE TITLE
Question: Do init in extra function or in constructor?

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#19]
My thinking is that a constructor should not throw exception. Therefore its better to have an extra init-function, which can be tested separately. 

**Affected classes:**
- [ ] Saft\Sparql\Query\AbstractQuery

**Comment by white-gecko** [comment]
But what is the instance worth if it can not be initialized? I think there is some discussion about this out there. I would prefer initialization in the constructor for now.

**Comment by k00ni** [comment]
Ok, i prefer that too. So i will remove separate init-functions and move that stuff into the constructor. Even if the constructor throws exception it should be fine.
