### ISSUE TITLE
Get rid of remaining PHPArray implementations

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#20]
PHPArray was removed as independent cache backend. It will be used in the Cache test suite only. QueryCache is still using it as independent cache backend.

**Comment by white-gecko** [comment]
I think in some cases, such as StatementIterator array an implementation can serve as a default platform independent implementation.

**Comment by k00ni** [comment]
As we discussed few days ago, i only meant the PHPArray cache backend. So i will remove remaining code, for instance in QueryCache.

**Comment by k00ni** [comment]
Last commit f9c13bc removed last occurrences of PHPArray in cache related files.
