### ISSUE TITLE
Switch minimum PHP version from 5.3 to 5.4?

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#33]
As you can see here http://php.net/supported-versions.php, PHP 5.3 is no longer supported anymore. Most of linux distributions like Debian or Ubuntu provide at least PHP 5.4. So i vote for a change of our minimum PHP version to 5.4.

**Comment by white-gecko** [comment]
But does anything in our software actually require features newer than PHP 5.3?

**Comment by k00ni** [comment]
Actually not, but if we wanna go with Dice for DI (#17) for instance, they recommend using at least their PHP 5.4---PHP5.5 branch.

**Comment by white-gecko** [comment]
Ok, so I would say our minimum PHP requirement always depend on the libraries minimum requirements or the PHP features minimum version. (The maximum of the minimum requirements)

Which means, if we decide to use Dice we will raise the minimum required PHP version to 5.4 or even 5.5.

**Comment by k00ni** [comment]
Seems Dice is working even with the PHP 5.3 branch, so we can leave the minimum required PHP version, for now :)
