### ISSUE TITLE
Port all remaining classes to the Impl-way

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#34]
We decided a while ago to define an interface for a certain task and implement a class, suffixed with Impl, which solves the task our way. If you as a developer want to use your own way to solve a task, you can do that. Saft will accept different implementation as long as they implement the according interface.

Remaining classes, which are not ported yet:
- [x] Query related classes
- [X] Result related classes

**Comment by k00ni** [comment]
Here are some further information about the changes of 841e8ec regarding to this issue. This commit ports all Result related classes to the Impl-way. But during that, i adapted their structure and connections. I will explain why.

## Situation before the change

Namespace: **Saft\Store\Result**
- **interface:**
  - Result
- **classes:** All the following classes were implementing the Result interface.
  - EmptResult
  - SetResult
  - StatementResult
  - ValueResult

Every class, which wanted to handle a Result instance, directly created EmptyResult, SetResult, ... . Doing it this way interfered with our DI-strategy and the approach of using an interface + Impl-class.

Furthermore Result was not really doing anything. And SetResult was implementing \Iterator-related methods, but it was code, which already existing somewhere else. 

## Situation after the change
- **interfaces:**
  - Result
  - SetResult
  - ValueResult
- **classes:**
  - SetResultImpl
  - StatementSetResultImpl - _Was renamed, to better fit its purpose and what it really is. Early it was StatementResult, but its a list, so Set in the name makes it more clear._
  - ValueResultImpl
  - EmptyResultImpl

There is no EmptyResult interface you may now wondering. It is, because it would be empty and its [bad practice](https://r.je/empty-interfaces-bad-practice.html) to use one. But there are is-methods to help you determine which type of Result you got:
- isEmptyResult
- isSetResult
- isStatementSetResult
- isValueResult

I leaved this methods almost untouched, only renamed isStatementResult to isStatementSetResult.

#### SetResult(Impl) and StatementSetResult(Impl)

From now on, there is the following structure:

```
SetResultImpl extends \ArrayIterator implements SetResult
^
|
`----- StatementSetResultImpl extends SetResultImpl
```

There is no abstract class Result anymore and it is more clear now, that both classes are lists and you can iterate over them. Re-using \ArrayIterator class saved me code to implement and led to a smaller code base.

From now on it is also possible to implement your own Result classes, just like in Saft\Rdf for instance. You can extend the ResultFactoryImpl or implement your own and create your special Result implementations.

**Comment by k00ni** [comment]
### Query related classes

Porting the statements made sense, because you may need support for Redland and therefore had to implement a Redland based set of Result classes. Result classes can be very strong tied up with the underlying store.

But i thought about changing the Query related classes and port to the Impl-way. But there is no reason why to do that. There is already a Query interface and a QueryFactory. So i will only rename the exiting classes and add Impl to them to have a clear naming (AskQuery => AskQueryImpl). Thats it.

Thoughts?

**Comment by white-gecko** [comment]
Sounds good

**Comment by k00ni** [comment]
Done with 2e9606f.
