### ISSUE TITLE
Document Backends, especially how to setup the Store backends

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#35]

**Comment by white-gecko** [comment]
The backend configuration and requirements documentation goes here: http://safting.github.io/doc/phpframework/backends/

**Comment by k00ni** [comment]
I wrote some documentation about:
- where to find info how to setup a Virtuoso server [here](http://safting.github.io/doc/phpframework/backends/virtuoso/#installation)
- how to setup the Virtuoso server to act as a full-fledged SPARQL endpoint for HttpStore [here](http://safting.github.io/doc/phpframework/backends/httpstore/#setup-a-sparql-endpoint-for-http-requests-using-virtuoso)

**Comment by k00ni** [comment]
I started a description about how to setup ARC2 [here](http://safting.github.io/doc/phpframework/backends/ARC2/). Lacks of example code and maybe further general information.
