### ISSUE TITLE
Create list of supported formats (Parser + Serializer)

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#37]
We need a list of format strings and their pendant of the real world. For instance rdfxml as format, which stands for RDF/XML. I would prefer the current usage from [EasyRdf](https://github.com/njh/easyrdf/blob/master/lib/Format.php#L253).
- rdf-json: `application/json`
- json-ld: `application/json`*
- rdfa: `text/html`
- rdf-xml: `application/rdf+xml`
- n-triples: `application/n-triples`
- n-quads: `application/n-quads`
- turtle: `text/turtle` (`application/x-turtle`, `application/turtle`)
- trig: `application/trig`

maybe:
- n3
- hdt

http://librdf.org/raptor/api/raptor-formats-types-index.html

**Comment by white-gecko** [comment]
We should also add MIME/Types

**Comment by k00ni** [comment]
Do you mean additionally or as a separate list? 

What i mean is a simple list for the serializations:
- json
- jsonld
- nquads
- ntriples
- rdfa
- rdfxml
- sparql-xml
- turtle

Once we set it fixed, we use it in all our Parser and Serializer implementations. And foreign developers can read that in our documentation so they use the same terms.

**Comment by white-gecko** [comment]
Don't know maybe we can expose this as some kind of Helper which has some XtoY methods, where X and Y can be one of formats (internal string representation), mimetype, name (e.g. "Turtle", "RDF/XML", "N-Triples", …) or file endings (".ttl", ".rdf", ".nt", …)

**Comment by k00ni** [comment]
I port existing serializer and parser implementations (EasyRdf, Saft\Data) to the new terms. Furthermore, i created some documentation about the new terms and how they are supported: http://safting.github.io/doc/phpframework/data/

What is left is the MIME-type handling. I forgot how we wanted to handle that... Was it that we let it as it is now for _0.1_ and add new methods to parsers/serializers to handle MIME-types in _0.2_ or did we decided to support that already for 0.1?

**Comment by white-gecko** [comment]
We should support that in 0.1 already. I think the best would be to handle it by some translation method `mimeToFormat($mimeTypeString)` and `formatToMime($formatString)`.

**Comment by k00ni** [comment]
I added a further Utils class namend `SerializationUtils` in `Saft\Data` (with basic tests). We can move its methods to better locations, if we want, but for now it should be fine.
