### ISSUE TITLE
getMatchingStatements doesn't return graph information

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#39]
Getting statements with `getMatchingStatements()` returns `Statement`s without graph, even though a specific graph was queried.

There is not test for that yet.

**Comment by k00ni** [comment]
Yes, that's a simple problem. 

But as i stated [here](https://github.com/SaftIng/Saft/issues/38#issuecomment-104671773), i think if the graph was set to AnyPattern, the resulting statements have no graph as well (property graph = null).

**Comment by white-gecko** [comment]
No the property `$graph` in this case actually has to be the same as specified when calling `getMatchingStatements()`. Else I'd expect it to be from the default graph.

**Comment by k00ni** [comment]
Do we need a certain class to express the default graph?

**Comment by white-gecko** [comment]
I think no, it should be just the “default” case if non is specified …

**Comment by k00ni** [comment]
With commit 590e165, current behavior is:
- if graph was specified in the statement, all result statements have the same graph
- if graph was null in the statement, all result statements have null as graph

Ok?

**Comment by white-gecko** [comment]
yes, but the case:
- if graph was anypattern the resulting statements need the correct graph

is missing.

**Comment by k00ni** [comment]
Ok, i leave that to you. I guess you want to solve that in the way you described [here](https://github.com/SaftIng/Saft/issues/38#issuecomment-104674972)?
