### ISSUE TITLE
Store implementations have to throw StoreExceptions (or subclasses)

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#41]
Adapt classes and comments.

Furthermore the Store interface needs a notice about the Exception handling and that it could differ from implementation to implementation.

**Comment by white-gecko** [comment]
I think we have to think about the whole Exception handling in general. For now I would just throw normal `\Exception`s which we than can grep and replace by the correct Exceptions as needed.

**Comment by k00ni** [comment]
> I think we have to think about the whole Exception handling in general. For now I would just throw normal \Exceptions which we than can grep and replace by the correct Exceptions as needed.

Commit 5a553ae implements that. (i was mistaken with the issue ID)

**Comment by k00ni** [comment]
Because there is no real benefit having custom exceptions, i will close this for now.
