### ISSUE TITLE
Implement EqualsSparqlConstraint with Query Object

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#42]
The `EqualsSparqlConstraint` should be implemented by creating query objects from the SPARQL queries string which have to be compared and then compare the semantics/relevant parts of the objects.

This will also resolve the skipped tests in `StoreAbstractTest` by just checking for variables at the same positions. Maybe we also have to introduce some `SparqlMatchesPatternConstraint`.

**Comment by k00ni** [comment]
I added RegexMatchConstraint.php before which uses regular expressions to match certain queries. It works good and all old tests, which based on EqualsSparqlConstraint, were ported. So i think that issue is done.
