### ISSUE TITLE
assertIteratorContent in TestCase

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#43]
`assertIteratorContent` in `TestCase` uses the PHP `serialize()` method on statement objects for comparison. This will not give us semantic equality, because different backend implementations will differ in their PHP serialization.

**Comment by white-gecko** [comment]
is this fixed?

**Comment by k00ni** [comment]
The current implementation uses serialize(). But the result will differ for different implementations, so we need another solution to compare instances.

**Comment by white-gecko** [comment]
Should be fixed in 1b622fb66005438c0a707cda59a24aaa8260e63a

**Comment by k00ni** [comment]
Thats a good way to solve this.
