### ISSUE TITLE
Move Cache to own repo

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#49]
Move Cache part e.g. to SaftIng/Sprudel repo with backends accordingly

**Comment by k00ni** [comment]
Using [Nette\Caching](https://github.com/nette/caching) seems very promising. It provides MemcacheD and file backend too, so i think we just use it for now and don't create just-another-cache-lib (there a couple already there).

Removed:
- Saft\Addition\FileCache
- Saft\Addition\MemcacheD
- Saft\Cache

Important changes:
- QueryCache test simplified and it only uses a memory storage
  (PHP-array) to store entries
- removed all cache related stuff from the test-config.yml.dist
  (existing one does not have to be updated, cache related stuff
  will be just ignored)

**Comment by k00ni** [comment]
#### Thoughts about the application level

Just wanted to say, that at the application level, you have to use Nette\Caching. That means that if you are in, lets say, Drupal, you must include the Nette\Caching library among your existing caching solution. 

I thought about provide interfaces that you can implement with your existing cache classes. But i always ended up with scenarios, where you have to add more code-bloat to your project without gaining any advance in time or code or whatever. 

We might change that in the future, but for now its a good solution in my opinion. So closed for now.
