### ISSUE TITLE
Remove setter methods from Statement

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#51]
The setter methods on Statement should be removed, because a Statement is immutable. It would cause new problems to consider if we want Statement object to be mutable.
Objects should not be "reused".

Thus the methods `setGraph()`, `setObject()`, `setPredicate()` and `setSubject()` should be removed.

RFC

**Comment by k00ni** [comment]
Sure, no problem. But i just want to state that we remove a lot of handy stuff. Can you remove these functions?

**Comment by white-gecko** [comment]
In which case is it handy?
