### ISSUE TITLE
Finalize API for 0.1 release

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#52]
For each class and method we have to check …
- [ ] … if the naming is precise and correct
- [ ] … if the parameters are necessary/enough
- [ ] … if the semantics of the method is clearly documented as intended in the doc block

Further we have to decide on each method whether it is part of the API by setting a `@api` tag, maybe together with the API version/ API level

**Comment by white-gecko** [comment]
We are starting with this at http://safting.github.io/doc/#application-programming-interface

**Comment by k00ni** [comment]
As mentioned before, i would like to add all interfaces and the abstract classes to the API, even some classes (NodeUtils for instance). For more information about that, please look [here](http://safting.github.io/doc/apiinfo/).

Do you think that we should tag each method with a since-tag? Or do we only set the api-tag at the head of the file?

**Comment by white-gecko** [comment]
`@since` tag for each method is important. We can even list the parameters as specified here: https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#817-since

**Comment by k00ni** [comment]
I added api- and since-tags for all core packages except Saft\Sparql. Current status is here: http://safting.github.io/doc/apiinfo/

My last commit 62e56b2 also contained a couple of code nice ups about reformating method comments.

**Comment by k00ni** [comment]
Closed due inactivity. In my opinion the mentioned points are ongoing tasks and should be checked before each minor or major release. So moved to 0.2

**Comment by k00ni** [comment]
Due the recent 0.2 release i close this. We should consider checking your points from time to time regardless of the version number.
