### ISSUE TITLE
Only allow strings as literal value

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#53]
The value of a literal should be given as a string. In this way and by always treating it as string we can ensure that the value remains the same. Especially we don't get problems with whether to represent a boolean as "true" or "false" or as "1" or "0". And we wouldn't face the question how to treat a PHP-boolean, if the datatype is string …

RFC

**Comment by k00ni** [comment]
How do you ensure that the given value is a string?

I suggest to use the is_string function. Would you add further checks to avoid memory leaks because the string is to large and such stuff?

**Comment by white-gecko** [comment]
Are there memory leaks for large strings in PHP?

For now I would check it with `is_string()` if there will be type hinting for strings, we can use that.

**Comment by k00ni** [comment]
Lets discuss this in the chat room further.
