### ISSUE TITLE
StoreChain has to become ChainFactory

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#6]
The ChainFactory takes a chain configuration (config array), creates the required store instances and configures their successors.

**Comment by k00ni** [comment]
Fixed with db5e30d.

**Comment by k00ni** [comment]
We decided to remove ChainFactory, because it relies on StoreFactory which needs a DI-container to work. But we wont introduce one at the framework level, so we decided to remove StoreFactory and therefore ChainFactory too.

For more information have a look at #17.
