### ISSUE TITLE
ARC2: Check in createGraph before creating a new graph, that no one already exists

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#67]
Currently, each time you call createGraph, a new graph instance gets created via ARC2.

**Comment by white-gecko** [comment]
How does ARC2 create a graph instance if one exists already?

**Comment by k00ni** [comment]
It handles RDF information inside tables and i saw, that after a createGraph call, it created according entries in these tables. Have to get more into that problem to be more specific, but i think a simple SQL-query to check for related entries should be enough.
