### ISSUE TITLE
NQuad serialization needs to replace special chars

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#69]
Chars like ä, ö, ü etc need to be transformed otherwise tools like rapper throw errors. I currently dont know how to call these chars, which replace the special chars.

**Comment by pfrischmuth** [comment]
This includes escaping of literal strings as defined in the [N-Quads Grammar](https://www.w3.org/TR/n-quads/#sec-grammar).

In addition to unicode characters, some special characters like '"', '\', LF and CR need to be escaped, too.

I will create a pull request that adds escaping for the latter special characters, but this needs to be extended for unicode characters.

**Comment by k00ni** [comment]
Partly fixed by 36dc54f.

**Comment by k00ni** [comment]
Removed NQuadsParser class with `1.0` release, because it gets owned by hardf component. Just use hardf in the future.

**Main disadvantages:**
* this bug
* needs to load the whole file
* no chunking support
