### ISSUE TITLE
Datatypes of Literals rework

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#7]
Problematic cases:
- "..."^^sysont:markdown
- "5"^^xsd:string vs. 5^^xsd:integer

Change current behavior:
- if value of literal is without data type, it is an untyped literal
- if value of literal is given explicit, it will be used

**Comment by k00ni** [comment]
We decided, that we store literal values as strings, but provide their type. So if you need the _real_ type later on, you can cast it on your own. 

We tried to map literal types to PHP types (string, bool, ...) but the casting and transformation sucks and is not always accurate.

**Comment by white-gecko** [comment]
> - if value of literal is without data type, it is an untyped literal
> - if value of literal is given explicit, it will be used

According to http://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal the datatype is always set

**Comment by white-gecko** [comment]
Closed with 1e6a7400ef8f44364120831f879ca111e0939510
