### ISSUE TITLE
Data: Implement RDF and N-Triple parser

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#80]
Due massive problems with EasyRdf and ARC2 parsing XML documents properly i decided to implement these two parsers by myself.

A RDF/XML parser can be implemented using Sabre/XML (https://github.com/fruux/sabre-xml). It provides an array like approach. (First local tests ran fine)

The N-Triples parser can be implemented using simple regex due the fact, that n-triples is very restrictive with special chars.

**Comment by white-gecko** [comment]
We can also copy and improve the parsers from https://github.com/AKSW/Erfurt .

**Comment by k00ni** [comment]
You are right, how is the support/state of these in Erfurt?

I experienced that Erfurt generates invalid RDF/XML when export a model. Try using [this RDF/XML export](http://aksw.org/model/export/?m=http%3A%2F%2Faksw.org%2F&f=rdfxml) and let it check with http://www.xmlvalidation.com/. It shows me 286 errors. Because of that, i guess at least RDF/XML handling is not that well supported in Erfurt. Furthermore Erfurt exported stuff is not readable by EasyRdf.

**Comment by k00ni** [comment]
I implemented the first version of the RDFXMLParser [here](https://github.com/SaftIng/Saft/blob/master/src/Saft/Data/RDFXMLParser.php#L59). It seems to be nearly complete. Using it, we avoid further hassle with XML-parsing, because the underlying library cares about that.

**Comment by white-gecko** [comment]
Nevertheless, how the support/state of the parsers and serializers in Erfurt are, we should have a good test coverage and continue implementing/applying the W3C parser and serializer test cases.

**Comment by k00ni** [comment]
Agreed.

**Comment by k00ni** [comment]
Our new [parser](https://github.com/SaftIng/Saft/blob/master/src/Saft/Data/NQuadsParser.php) supports NQuads and NTriples. I tested it with basic examples.

If we have time, they should be tested with W3C test cases, as you suggested.
