### ISSUE TITLE
add https://github.com/pietercolpaert/hardf as addition?

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#88]
https://github.com/pietercolpaert/hardf seems a good alternative to EasyRdf and ARC2, which are both not maintained anymore. Further, its performance is quite good in comparison.

**Comment by white-gecko** [comment]
Sounds good. Lets integrate it :-)

**Comment by k00ni** [comment]
Will you? :D

**Comment by k00ni** [comment]
Reopened. I would like to let this open until we finished the job.

**Comment by k00ni** [comment]
I added a basic Parser implementation for hardf.

**Comment by white-gecko** [comment]
Sounds like a good idea.

Am 29. Mai 2017 18:00:56 MESZ schrieb Konrad Abicht <notifications@github.com>:
>I added a basic Parser implementation for hardf.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/SaftIng/Saft/issues/88#issuecomment-304692707

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
