### ISSUE TITLE
Change Saft license to MIT, Apache License, LGPL, ... or dual license?

### ISSUE THREAD

**Issue by k00ni** [SaftIng/Saft#90]
I would like to adapt the Saft license to not force thirdparty libraries to be GPL as well. With the GPL i am worried to violate my own license, if i use it in a non-GPL software (which i currently [am](https://github.com/k00ni/knorke)). Sure, we decided to use GPL to enforce that (distributed) modifications of the code are GPL too. But if i only implement interfaces of Saft, my software needs to be GPL as well.

@white-gecko: Would you use either [MIT](https://choosealicense.com/licenses/mit/), [Apache License](https://choosealicense.com/licenses/apache-2.0/) or even [LGPL](https://choosealicense.com/licenses/lgpl-3.0/) as new license? If i understand it right, LGPL would be proprietary-friendly enough [[1]](http://www.it-rechts-praxis.de/meldungen/Open-Source-Kommerzielle-Nutzung-von-LGPL-Libraries-12) for my use case.

The following people have to apply:
* [x] @k00ni
* [x] @white-gecko 
* [x] @vitaB (got a mail from him today in which he gave us the permission to change the license as we want)
* [x] @oliverskawronek (gave permission on [8th June 2017](https://github.com/SaftIng/Saft/issues/90#issuecomment-307126086))
* [x] @pfrischmuth (gave permission on 9th June 2017)

**Comment by k00ni** [comment]
Maybe important: https://github.com/SaftIng/Saft/pull/85

**Comment by k00ni** [comment]
@oliverskawronek: Can you give us the permission to change the license of Saft to whatever we want? (referenced you here, because your studserv mail couldn't be delivered)

**Comment by k00ni** [comment]
@pfrischmuth: Any complains about changing the license of Saft? Do you give us permission to license your code under any license we want?

**Comment by olskaw** [comment]
Yes, you have the permission to change the license of Saft to whatever we want. Have fun :)

**Comment by k00ni** [comment]
@oliverskawronek: Thanks!

**Comment by k00ni** [comment]
@white-gecko: We got approval from everybody. The next question is, which license is suitable for us? Which do you prefer (besides GPL :P)?

**Comment by k00ni** [comment]
**I would like to change the license to MIT**. This gives the most freedom for code usage. Major libraries/frameworks like symfony or jQuery also using this license.

**Comment by white-gecko** [comment]
ok

**Comment by k00ni** [comment]
Further discussion in the related pull request.
